import {
  Activity,
  Apple,
  BadgeCheck,
  Calculator,
  CalendarClock,
  CalendarDays,
  Circle,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CreditCard,
  DoorOpen,
  Dumbbell,
  Facebook,
  Flame,
  GlassWater,
  Headset,
  HeartPulse,
  Instagram,
  LineChart,
  Lock,
  MessageCircle,
  Move,
  ParkingSquare,
  Percent,
  Scale,
  ShowerHead,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  UserCheck,
  Users,
  Weight,
  Wind,
  Youtube,
  Zap,
} from 'lucide-react'

// Explicit registry (only the icons referenced from data files) so the bundle
// tree-shakes instead of pulling in the entire icon library.
const REGISTRY = {
  Activity,
  Apple,
  BadgeCheck,
  Calculator,
  CalendarClock,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CreditCard,
  DoorOpen,
  Dumbbell,
  Facebook,
  Flame,
  GlassWater,
  Headset,
  HeartPulse,
  Instagram,
  LineChart,
  Lock,
  MessageCircle,
  Move,
  ParkingSquare,
  Percent,
  Scale,
  ShowerHead,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  UserCheck,
  Users,
  Weight,
  Wind,
  Youtube,
  Zap,
}

// Renders a Lucide icon by its string name (from data files).
export default function Icon({ name, className = '', ...props }) {
  const Cmp = REGISTRY[name] || Circle
  return <Cmp className={className} {...props} />
}
